INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (1,'Sulfato de Sodio','Kilogramo','5024','510.23');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (2,'Hipoclorito de Potasio','Kilogramo','8904','2117.42');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (3,'Sulfato de Manganeso','Kilogramo','5274','1710.35');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (4,'Dietildamida','Kilogramo','7878','2588.71');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (5,'Agua Oxigenada','Kilogramo','6790','4076.69');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (6,'Benceno','Kilogramo','6253','3444.18');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (7,'Anhidro acetico','Kilogramo','7623','4589.66');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (8,'Benzaldehido','Kilogramo','8372','4494.01');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (9,'Carbonato de Potasio','Kilogramo','5245','3350.4');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (10,'Acetico Glacial','Kilogramo','9651','2730.16');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (11,'Metilico','Kilogramo','8708','1514.32');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (12,'Alcohol Isopropilico','Kilogramo','8722','775.41');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (13,'Cloruro de acetilo','Kilogramo','9152','4251.24');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (14,'Bromobencilo','Kilogramo','8419','3880.3');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (15,'Tricloroetileno','Kilogramo','5290','1970.33');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (16,'Bicarbonato de sodio','Kilogramo','9430','4570.01');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (17,'Oxido de Calcio','Kilogramo','9250','4214.96');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (18,'Xilenos','Kilogramo','5468','4011.18');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (19,'Hidroxido de Sodio','Kilogramo','6683','3544.5');
INSERT INTO Materia_Prima (`idMateriaPrima`,`Nombre`,`UnidadMedida`,`CantidadStock`,`Precio`) VALUES (20,'Amoniaco','Kilogramo','7699','1910.69');
