INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (1,'Clary','Barlace','cbarlace0@wordpress.com','388 Northwestern Way','+86-488-680-1265');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (2,'Feodora','Kaasman','fkaasman1@elpais.com','601 Maryland Circle','+351-215-658-9549');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (3,'Michele','Hyams','mhyams2@ask.com','78 Dixon Plaza','+62-236-660-3623');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (4,'Barris','Deave','bdeave3@columbia.edu','03 Longview Park','+51-113-749-9114');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (5,'Melita','Isselee','misselee4@hubpages.com','99161 Village Green Parkway','+86-988-574-8747');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (6,'Mara','Rashleigh','mrashleigh5@bloomberg.com','40 Old Gate Drive','+234-328-691-0491');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (7,'Brenna','Prettyman','bprettyman6@nymag.com','155 Crest Line Parkway','+86-925-155-7671');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (8,'Nate','Willmott','nwillmott7@exblog.jp','9493 Northfield Point','+86-174-448-0365');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (9,'Christen','Cranmore','ccranmore8@intel.com','5 Arizona Lane','+354-953-317-8223');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (10,'Marthena','Lesor','mlesor9@360.cn','83718 Mandrake Park','+255-761-414-5204');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (11,'Lisabeth','Yourell','lyourella@wikia.com','1164 Thompson Junction','+63-323-740-6983');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (12,'Merralee','Sacher','msacherb@paginegialle.it','67 Jenna Place','+62-604-956-0254');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (13,'Jasmin','Lisett','jlisettc@amazon.com','4200 Monument Trail','+374-223-177-0140');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (14,'Beulah','Stigell','bstigelld@amazonaws.com','417 Prairie Rose Place','+66-711-169-7298');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (15,'Ardelia','Perillo','aperilloe@barnesandnoble.com','6 Bultman Center','+63-593-587-5820');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (16,'Maegan','Yokley','myokleyf@jimdo.com','86826 Red Cloud Place','+62-562-829-5801');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (17,'Clementina','Tavner','ctavnerg@blogger.com','2 Cody Parkway','+1-212-145-4965');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (18,'Janey','Arch','jarchh@discuz.net','716 Morrow Place','+55-566-447-3927');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (19,'Mercie','Sherebrooke','msherebrookei@tripod.com','204 Elgar Hill','+385-916-419-9757');
INSERT INTO Usuarios (`idUsuario`,`Nombre`,`Apellido`,`Email`,`Direccion`,`Telefono`) VALUES (20,'Armando','Hurdwell','ahurdwellj@feedburner.com','53635 Valley Edge Court','+62-398-247-1831');
